package si.fri.rso.reservations.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import si.fri.rso.reservations.models.entities.Reservation;
import si.fri.rso.reservations.models.repositories.ReservationRepository;

import java.util.Optional;

@Component
public class ReservationService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ReservationRepository reservationRepository;


    public Reservation addReservation(Reservation s){
        return reservationRepository.save(s);
    }

    public Iterable<Reservation> getAllReservations(){
        return reservationRepository.findAll();
    }

    public Optional<Reservation> getReservationByID(Integer id) { return reservationRepository.findTopByStationOrderByIdDesc(id); }
}
