package si.fri.rso.reservations.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import si.fri.rso.reservations.models.entities.Station;
import si.fri.rso.reservations.models.repositories.StationRepository;

import java.util.Optional;

@Component
public class StationService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StationRepository stationRepository;


    public Station updateStation(Station s){
        return stationRepository.save(s);
    }

    public Iterable<Station> getAllStations(){
        return stationRepository.findAll();
    }

    public Optional<Station> getStationByID(Integer id) { return stationRepository.findById(id); }
}
